name: Build and deploy container app to Azure Web App 

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://dregistrycm.azurecr.io/
        username: ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }}
        password: ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: dregistrycm.azurecr.io/${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }}/new1:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'mywebapp-00'
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_MYWEBAPP_PUBLISH_PROFILE }}
        images: 'dregistrycm.azurecr.io/${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }}/new1:${{ github.sha }}'
